#ifndef __EasyCrossPlatformFile__
	#define __EasyCrossPlatformFile__
	#include <EasyCP_Common.h>
	#include <XSYDMultiTask.h>
	#include <XSYDFileIO.h>
	#include <XSYDChrono.h>
	#include <XSYDMySQL.h>
	#include <XSYDEncryption.h>
	#include <XSYDRequest.h>
	#include <XSYDJson.h>
	#include <XSYDTCPSocket.h>
	#include <XSYDUDPSocket.h>
	#include <XSYDDNS.h>
#endif //__EasyCrossPlatformFile__