#ifndef __EasyCrossPlatformFile__
	#define __EasyCrossPlatformFile__
	#include "EasyCP_Common.h"
	#include "XSYDMultiTask.h"
	#include "XSYDFileIO.h"
	#include "XSYDTCPSocket.h"
	#include "XSYDUDPSocket.h"
	#include "XSYDAsyncTCPServer.h"
	#include "XSYDChrono.h"
#endif //__EasyCrossPlatformFile__