#ifndef __EasyCrossPlatformFile__
	#define __EasyCrossPlatformFile__
	#include "EasyCP_Common.h"
	#include "XSYDMultiTask.h"
	#include "XSYDFileIO.h"
	#include "XSYDTCPSocket.h"
	#include "XSYDUDPSocket.h"
	#include "XSYDAsyncTCPServer.h"
	#include "XSYDChrono.h"
	#include "XSYDMySQL.h"
	#include "XSYDEncryption.h"
	#include "XSYDRequest.h"
	#include "XSYDJson.h"
#endif //__EasyCrossPlatformFile__